import cv2
import math

MODE = 'intro'
PATH = 'C:/Users/Kyungmin Kim/Desktop/TP'
FONT = cv2.FONT_HERSHEY_SIMPLEX
ALBUM = 150
WIDTH = 640
HEIGHT = 480
REGION = 100
ARROW = 64
SPRITE = 64
HALF_WIDTH_LEFT = (WIDTH - REGION) // 2
HALF_WIDTH_RIGHT = (WIDTH + REGION) // 2
HALF_HEIGHT_UP = (HEIGHT - REGION) // 2
HALF_HEIGHT_DOWN = (HEIGHT + REGION) // 2
MIN_THRESHOLD = 200
MAX_THRESHOLD = 3000

LEVEL = 4
SQRT = math.sqrt(2)
GLOW_FADE = 15
SQRT_2 = 1.414
